name: Sync GHCR to Aliyun

on:
  workflow_dispatch: # 允许我们手动触发

jobs:
  sync-to-aliyun:
    name: Sync Image from GHCR to Aliyun
    runs-on: ubuntu-latest
    
    # 定义我们要同步的镜像
    env:
      SOURCE_IMAGE: ghcr.io/claudia312k/agent_ai:latest
      
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 第一步：登录到 GitHub Packages (ghcr.io)
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 自动生成的 Token

      # 第二步：登录到阿里云 ACR
      - name: Login to Aliyun Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      # 第三步：拉取源镜像
      - name: Pull image from GHCR
        run: docker pull ${{ env.SOURCE_IMAGE }}

      # 第四步：准备新的阿里云 Tag
      - name: Tag image for Aliyun
        run: |
          # 拼接出阿里云的完整镜像名
          NEW_TAG="${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/agent_ai:latest"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          
          # 给镜像打上新 Tag
          docker tag ${{ env.SOURCE_IMAGE }} $NEW_TAG

      # 第五步：推送到阿里云
      - name: Push image to Aliyun
        run: docker push ${{ env.NEW_TAG }}
