name: Debug Aliyun Login

on:
  workflow_dispatch: # 只允许手动触发

jobs:
  debug-login:
    name: Test Aliyun Login
    runs-on: ubuntu-latest
    steps:
      - name: Check if secrets are loaded
        run: |
          if [ -z "${{ secrets.ALIYUN_REGISTRY_USER }}" ]; then
            echo "::error::ALIYUN_REGISTRY_USER secret is EMPTY or NOT SET."
            exit 1
          else
            echo "✅ SUCCESS: ALIYUN_REGISTRY_USER secret is loaded."
          fi

          if [ -z "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}" ]; then
            echo "::error::ALIYUN_REGISTRY_PASSWORD secret is EMPTY or NOT SET."
            exit 1
          else
            echo "✅ SUCCESS: ALIYUN_REGISTRY_PASSWORD secret is loaded."
          fi
          
          if [ -z "${{ secrets.ALIYUN_REGISTRY }}" ]; then
            echo "::error::ALIYUN_REGISTRY secret is EMPTY or NOT SET."
            exit 1
          else
            echo "✅ SUCCESS: ALIYUN_REGISTRY secret is loaded."
          fi

      - name: Attempt to Login to Aliyun Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
